namespace: bcoca
name: misc
version: 0.0.1
authors:
  - bcoca
description: misc stuff
license: GPLv3+
tags:
repository: https://github.com/bcoca/misc-collection
documentation: use the source, Luke!
homepage: https://github.com/bcoca/misc-collection
issues: https://github.com/bcoca/misc-collection/issues
readme: docs/README.txt
